### ISSUE TITLE
Gallery of posted media files shows text from post

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub-modules-gallery#11] opened 2017-06-10 16:40 UTC
Gallery of posted media files shows full text from post for some images/posts.
![schermafbeelding 2017-06-10 om 18 39 00](https://user-images.githubusercontent.com/6781157/27004616-317ac73a-4e0c-11e7-892d-39ebb2487484.png)

Martin

**Comment by BastusIII** [comment] 2017-06-28 13:53
Hi Martin,

It was caused by insufficient html encoding of the post's description and will be fixed with the next version.

Basti

**Closed by BastusIII** 2017-06-28 13:53 UTC

**Comment by martinbeek** [comment] 2017-06-28 13:58
Thanks! Great! 
Love this module!
